name = "DeepBoltzmannMachines"
uuid = "b034215e-01f4-4cb9-9983-11f96926eae2"
authors = ["Jorge Fernandez-de-Cossio-Diaz <j.cossio.diaz@gmail.com>"]
version = "0.1.0"

[deps]
RestrictedBoltzmannMachines = "12e6b396-7db5-4506-8cb6-664a4fe1e50e"

[compat]
julia = "1.5"
